 machine.initCyclicRead('MAIN.Lift1')
 machine.initCyclicRead("MAIN.Picker1")
 machine.initCyclicRead("MAIN.pm2")
 machine.initCyclicRead("MAIN.PiperModules")
 machine.setReadGroupMaxFrequency('global',50)
 machine.initCyclicRead('MAIN.Lift2')
 machine.initCyclicRead('MAIN.Lift3')
 machine.initCyclicRead('MAIN.Lift4')
 machine.initCyclicRead('MAIN.Lift5')
// machine.initCyclicRead('MAIN.Lift6')
